### ISSUE TITLE
Uncaught TypeError: react_1.createStitches is not a function

### ISSUE THREAD

**Issue by jpinzon0080** [jcmnunes/editor#31]
```
Uncaught TypeError: react_1.createStitches is not a function
    at Object../node_modules/@binarycapsule/ui-capsules/dist/stitches.config.js (stitches.config.js:7:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Object../node_modules/@binarycapsule/ui-capsules/dist/Text/Text.js (Text.js:4:1)
    at Object.options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at Object../node_modules/@binarycapsule/ui-capsules/dist/Alert/Alert.js (Alert.js:8:1)
    at Object.options.factory (react refresh:6:1)
```

I am trying to use this library but am getting this error. Could anyone help me fix this issue? Thanks in advance.

**Comment by jcmnunes** [comment]
Hi @jpinzon0080, 

I'm guessing you don't have [Stitches](https://stitches.dev/) installed on your project.

But please, don't use this library in any real project. It is just a personal breakable toy that I use to test some ideas and to add to my developer portfolio (I added that to the README).

If you need a Prosemirror based editor [tiptap](https://tiptap.dev/) might be a good choice.

**Comment by jpinzon0080** [comment]
Hi @jcmnunes, thank you for your suggestion. I need an editor that works exactly the same as the Linear app editor. And your demo app is working perfectly. Is there any other library that I can use to build Linear app like editor asap?
